# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
            ],
            options={
                'verbose_name': 'cliente',
                'db_table': 'clientes',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('data', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web_aplication.Cliente')),
            ],
            options={
                'verbose_name': 'compra',
                'db_table': 'compras',
                'verbose_name_plural': 'compras',
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18)),
            ],
            options={
                'verbose_name': 'fabricante',
                'db_table': 'fabricantes',
                'verbose_name_plural': 'fabricantes',
            },
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor_unit', models.FloatField()),
                ('compras', models.ManyToManyField(through='web_aplication.Compra', to='web_aplication.Cliente')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_aplication.Fabricante')),
            ],
            options={
                'verbose_name': 'peca',
                'db_table': 'pecas',
                'verbose_name_plural': 'pecas',
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='peca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web_aplication.Peca'),
        ),
    ]
