# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_aplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='valor_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
